### ISSUE TITLE
Game breaking problem with UltimateClaims from version 2.0.0 onward 

### ISSUE THREAD

**Issue by PlastoresTM** [craftaro/UltimateClaims#35]
**This is an urgent issue for any survival server that uses UltimateClaims in version 1.20.*, I hope you take a look at this as soon as possible, as it has major effects on all survival servers and their player's data.** 

Starting from version 2.0.0 to the newest 2.0.1 and 2.1.0, UltimateClaims seems to have failed at writing data into the plugin's database and failed to convert the old version of the database to the new plugin. 

First of all, after updating from an older version of UC to anything from 2.0.0 onward, it would show an error message and fail to convert the old database to the new version, which affects the player's ability to claim after the update. Not only that but 2.0.0 also seems to fail at saving the claim data after a server restart, as testing from a fresh server shows that even with a completely fresh install, it would still fail to save the claims made by players from every other server restart. 

The way I tested this for all the versions from 2.0.0 onward is to create a new paper server, install the UC jar file, and create a claim in-game, then I restart the server and check the claim in-game again. From my testing, after the first restart, the claim would be fine, so I dissolved that claim created a new one and then restarted the server. And after that restart, my claim would be gone, so I go on and create another one, and then restart again. This time, however, my claim would be saved again, for whatever reasons. This is the pattern that I was able to capture after testing for a few days with the 2.0.0 onward version of UC.

**This is the error that shows when it fails to save player's claim data after a server restart:**
![image](https://github.com/craftaro/UltimateClaims/assets/101139557/5f015386-2012-4b2c-a37d-b110c8885a85)

**This is the error that shows after updating to a new version of UC with a old database:**
![image](https://github.com/craftaro/UltimateClaims/assets/101139557/429bc2ab-3cb8-4a96-a216-cdb592390b85)

**Comment by SpraxDev** [comment]
## Claims not getting saved on server shutdown
I was able to replicate the issue and I think I've prepared a fix which will be part of the next update.

## Errors when upgrading v1 databases
This is supposed to be fixed in UltimateClaims v2.0.1 and I cannot replicate the issue in v2.1.0 (with a small v1 database).

Are you sure you used at least v2.0.1? If yes or the error persists, would you be comfortable sharing your old/v1 database with me for further testing? (publicly here or privately via Discord [`@sprax`] or something else)

## "Claim ID ## has no owner for some reason"
Can replicate this issue even with a clean database and the fix applied for server-shutdown etc.

Still trying to find out why and how this breaks...
